import OpenAI from 'openai';
import {
  type ToolContext,
  formatError,
} from '@/lib/tools/helpers';
import { getStorage } from '@/lib/storage/storage-manager';

// Lazy initialization to avoid errors when OPENAI_API_KEY is not set at module load time
let openai: OpenAI | null = null;
function getOpenAI(): OpenAI {
  if (!openai) {
    openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }
  return openai;
}

interface GenerateImageInput {
  prompt: string;
  size?: '1024x1024' | '1792x1024' | '1024x1792';
  quality?: 'standard' | 'hd';
  style?: 'vivid' | 'natural';
  filename?: string;
}

interface GeneratedImage {
  storage_path: string;
  url: string;
  prompt: string;
  size: string;
  revised_prompt?: string;
  filename: string;
}

interface GenerateImageOutput {
  success: boolean;
  image?: GeneratedImage;
  error?: string;
}

export default async function generate_image(
  input: GenerateImageInput,
  ctx: ToolContext
): Promise<GenerateImageOutput> {
  try {
    const {
      prompt,
      size = '1024x1024',
      quality = 'standard',
      style = 'vivid',
      filename: customFilename
    } = input;

    if (!prompt || prompt.trim().length === 0) {
      return {
        success: false,
        error: 'Prompt is required and cannot be empty'
      };
    }

    // Generate image with DALL-E 3
    console.log(`[generate_image] Generating image: "${prompt.substring(0, 50)}..."`);
    
    const response = await getOpenAI().images.generate({
      model: 'dall-e-3',
      prompt,
      n: 1,
      size,
      quality,
      style,
      response_format: 'url'
    });

    const imageData = response.data[0];
    if (!imageData || !imageData.url) {
      return {
        success: false,
        error: 'No image generated by DALL-E'
      };
    }

    // Download the image
    console.log('[generate_image] Downloading generated image...');
    const imageResponse = await fetch(imageData.url);
    if (!imageResponse.ok) {
      return {
        success: false,
        error: `Failed to download image: ${imageResponse.statusText}`
      };
    }

    const imageBuffer = Buffer.from(await imageResponse.arrayBuffer());

    // Generate filename
    const timestamp = Date.now();
    const filename = customFilename
      ? `${customFilename}_${timestamp}.png`
      : `dalle_${timestamp}.png`;

    // Save to storage
    const storage = getStorage();
    await storage.save(
      ctx.currentSpace,
      'images/generated',
      filename,
      imageBuffer
    );

    const relativePath = `storage/images/generated/${filename}`;

    console.log(`[generate_image] Image saved to: ${relativePath}`);

    return {
      success: true,
      image: {
        storage_path: relativePath,
        url: imageData.url,
        prompt,
        size,
        revised_prompt: imageData.revised_prompt,
        filename
      }
    };

  } catch (error: any) {
    console.error('[generate_image] Error:', error);
    
    if (error.code === 'content_policy_violation') {
      return {
        success: false,
        error: 'Image prompt violates content policy. Please revise your prompt.'
      };
    }

    return {
      success: false,
      error: formatError(error)
    };
  }
}
